version: "3.8"

services:
  pipeline:
    build: .
    container_name: pipeline_container
    volumes:
      # Mount host FASTQ directory (read-only)
      - ./fastqs:/data/fastqs:ro
      # Mount output directory (pipeline writes results here)
      - ./outputs:/data/outputs
      # Optional: mount COSMIC data if needed
      - ./cosmic:/data/cosmic:ro
    environment:
      # Environment variables the pipeline scripts can use
      - FASTQ_DIR=/data/fastqs
      - OUTPUT_DIR=/data/outputs
      - COSMIC_DIR=/data/cosmic
    working_dir: /pipeline
    command: ["/pipeline/pipeline_runner.sh", 
              "--fastq_dir", "/data/fastqs", 
              "--output_dir", "/data/outputs",
              "--cosmic", "/data/cosmic/Cosmic_CancerGeneCensus_Tsv_v101_GRCh37.tar"]

